title: "「何者か」にならなくても大丈夫。あなたの“好き”を必要とする人に届ける技術"
description: "世間の流行を追う必要はありません。今のあなたのままで、最初の1,000円を稼ぐ体験をしてみませんか？「自分には何もない」と思っている人こそ知ってほしい、SNSに頼りすぎない集客とファン作りの教科書。"
theme: minima
lang: ja

minima:
  skin: dark

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/
